CREATE SCHEMA IF NOT EXISTS `programs` ;
USE `programs` ;

CREATE TABLE  IF NOT EXISTS `programs`.`ListTemplate` (
  `PROGRAM` VARCHAR(500) NULL,
  `TIME_ADDED` DATETIME NOT NULL,
  `LAST_UPDATED` DATETIME NOT NULL,
)
